name: Desplegar Portafolio a GitHub Pages

on:
  push:
    branches: [ main ]

# PASO CLAVE 1: Darle permisos explícitos al servidor para escribir la rama gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # PASO CLAVE 2: Apuntar directamente al archivo .csproj en lugar de la solución (.sln)
    # NOTA: Si cambiaste el nombre de tu proyecto, asegúrate de escribir abajo el nombre exacto de tu nuevo archivo .csproj
    - name: Compilar y Publicar Proyecto
      run: dotnet publish portafolioV2.csproj -c Release -o release

    - name: Copiar index.html a 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # PASO CLAVE 3: El token automático de GitHub le dará el pase de acceso a la acción
    - name: Enviar a GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: release/wwwroot
        token: ${{ secrets.GITHUB_TOKEN }}